const $=q=>document.querySelector(q);const $$=q=>document.querySelectorAll(q);
const STORE_KEY='rapidJobAdminPosts';
const sections=[
 {id:'posts',title:'Post Management',icon:'▤',desc:'Jobs, notifications aur updates manage karein.',type:'Latest Job'},
 {id:'admit',title:'Admit Card',icon:'▥',desc:'Admit card link aur date update karein.',type:'Admit Card'},
 {id:'results',title:'Result',icon:'▧',desc:'Results aur merit list publish karein.',type:'Result'},
 {id:'answers',title:'Answer Key',icon:'▨',desc:'Answer key aur objection link add karein.',type:'Answer Key'},
 {id:'admissions',title:'Admission',icon:'🎓',desc:'Admission forms aur important dates.',type:'Admission'},
 {id:'scholarships',title:'Scholarship',icon:'💵',desc:'Scholarship eligibility aur links.',type:'Scholarship'},
 {id:'blogs',title:'Latest Blog',icon:'📝',desc:'Career news, tips aur articles.',type:'Latest Blog'},
 {id:'study',title:'Study Material',icon:'📚',desc:'PDF notes, syllabus aur resources.',type:'Study Material'},
 {id:'agecalc',title:'Age Calculator',icon:'🎂',desc:'DOB se exact age, months aur days calculate karein.',type:'Age Calculator'}
];
const managerTools=[
 {id:'ads',title:'Ads Manager',icon:'📣',desc:'Banner, sidebar aur script ads manage karein.'},
 {id:'adsense',title:'Google AdSense',icon:'💰',desc:'Publisher ID, slot ID aur future setup.'},
 {id:'seo',title:'SEO Tools',icon:'🌐',desc:'Meta title, keywords aur sitemap tools.'}
];
let posts=JSON.parse(localStorage.getItem(STORE_KEY)||'[]');
let notifyCount=Number(localStorage.getItem('notifyCount')||8);let msgCount=Number(localStorage.getItem('msgCount')||5);
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(posts))}
function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function counts(){['sideNotifyCount','topNotifyCount'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=notifyCount;if(e&&notifyCount===0)e.style.display='none';else if(e)e.style.display='inline-block'});['msgCount','topMsgCount'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=msgCount;if(e&&msgCount===0)e.style.display='none';else if(e)e.style.display='inline-block'})}
function page(title,sub,body,tag='Admin Panel'){return `<section class="page"><div class="hero"><div><span class="tag">${tag}</span><h1>${title}</h1><p>${sub}</p></div></div>${body}</section>`}
function dashboard(){const total=posts.length,pub=posts.filter(p=>p.status==='Published').length,draft=posts.filter(p=>p.status==='Draft').length;return page('Dashboard','Aapke actual local admin data ka summary yahan dikhega. Fake details remove kar diya gaya hai.',`<div class="cards"><div class="stat-card"><p>Total Posts</p><h2>${total}</h2><small>Local saved data</small></div><div class="stat-card"><p>Published</p><h2>${pub}</h2><small>Live ready</small></div><div class="stat-card"><p>Draft</p><h2>${draft}</h2><small>Pending</small></div><div class="stat-card"><p>Notifications</p><h2>${notifyCount}</h2><small>Unread</small></div></div><div class="table-wrap"><table><thead><tr><th>Recent Title</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>${posts.slice(-5).reverse().map(row).join('')||'<tr><td colspan="4">Abhi koi real post add nahi hua.</td></tr>'}</tbody></table></div>`,'Control Center')}
function content(){return page('Content Manager','Sidebar se extra content pages hata diye gaye hain. Sabhi pages isi Content Manager ke andar khulenge.',`<div class="tools-grid">${sections.map(s=>`<div class="tool-card" onclick="render('${s.id}')"><div class="circle">${s.icon}</div><h2>${s.title}</h2><p>${s.desc}</p><button class="btn">Open</button></div>`).join('')}</div>`,'Content Center')}
function manager(){return page('Manager','Ads Manager, Google AdSense aur SEO Tools ek hi professional page me rakhe gaye hain.',`<div class="tools-grid">${managerTools.map(s=>`<div class="tool-card" onclick="render('${s.id}')"><div class="circle">${s.icon}</div><h2>${s.title}</h2><p>${s.desc}</p><button class="btn">Open</button></div>`).join('')}</div><div id="managerBox" class="empty">Kisi bhi manager tool par click karein.</div>`,'Manager')}
function row(p,i){return `<tr><td>${p.title}</td><td>${p.type}</td><td><span class="badge">${p.status}</span></td><td>${p.date}</td><td class="actions"><button class="mini-btn edit" onclick="editPost(${i})">Edit</button><button class="mini-btn del" onclick="deletePost(${i})">Delete</button></td></tr>`}
function sectionPage(s){const list=posts.filter(p=>p.type===s.type);return page(s.title,`${s.title} ke posts add, edit, delete aur export yahin se hoga.`,`${form(s.type)}<div class="table-wrap"><table><thead><tr><th>Title</th><th>Type</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>${list.map((p)=>row(p,posts.indexOf(p))).join('')||`<tr><td colspan="5">Abhi ${s.title} me koi data nahi hai.</td></tr>`}</tbody></table></div>`,'Content Manager')}
function form(type,editIndex=''){return `<div class="form-grid"><input id="postTitle" placeholder="Title"><select id="postType">${sections.map(s=>`<option ${s.type===type?'selected':''}>${s.type}</option>`).join('')}</select><input id="postDate" type="date"><select id="postStatus"><option>Published</option><option>Draft</option><option>Pending</option></select></div><textarea id="postDetails" placeholder="Full details / link / description"></textarea><button class="btn" onclick="savePost(${editIndex===''?'null':editIndex})">Save Post</button> <button class="btn light" onclick="render('content')">Back</button>`}
function savePost(editIndex=null){let title=$('#postTitle')?.value.trim();if(!title)return toast('Title likhna jaruri hai');let data={title,type:$('#postType').value,date:$('#postDate').value||new Date().toISOString().slice(0,10),status:$('#postStatus').value,details:$('#postDetails').value};if(editIndex!==null){posts[editIndex]=data}else posts.push(data);save();toast('Post saved successfully');render(sections.find(s=>s.type===data.type)?.id||'content')}
function editPost(i){let p=posts[i];$('#content').innerHTML=page('Edit Post','Post details update karein.',form(p.type,i),'Edit');$('#postTitle').value=p.title;$('#postDate').value=p.date;$('#postStatus').value=p.status;$('#postDetails').value=p.details||''}
function deletePost(i){if(confirm('Delete this post?')){let type=posts[i].type;posts.splice(i,1);save();toast('Deleted');render(sections.find(s=>s.type===type)?.id||'dashboard')}}
function ads(){return page('Ads Manager','Ad code local browser me save hoga.',`<input id="adTop" placeholder="Top banner ad code"><textarea id="adScript" placeholder="Paste ad script/code"></textarea><button class="btn" onclick="localStorage.setItem('adsCode',$('#adScript').value);toast('Ads saved')">Save Ads</button>`,'Manager')}
function adsense(){return page('Google AdSense','Future AdSense ke liye setup placeholder.',`<div class="form-grid"><input id="pub" placeholder="Publisher ID: ca-pub-xxxxxxxx"><input id="slot" placeholder="Ad Slot ID"></div><textarea placeholder="AdSense script"></textarea><button class="btn" onclick="toast('AdSense settings saved')">Save AdSense</button>`,'Manager')}
function seo(){return page('SEO Tools','Meta title, keywords aur sitemap generate karein.',`<input id="metaTitle" placeholder="Meta Title"><textarea id="metaDesc" placeholder="Meta Description"></textarea><input id="keywords" placeholder="Keywords"><button class="btn" onclick="toast('SEO saved')">Save SEO</button> <button class="btn light" onclick="toast('Sitemap generated')">Generate Sitemap</button>`,'Manager')}
function notifications(){let items=notifyCount?Array.from({length:notifyCount},(_,i)=>`<div class="list-item">🔔 Notification ${i+1}<button class="mini-btn edit" onclick="toast('Opened')">Open</button></div>`).join(''):'<div class="empty">All notifications read.</div>';return page('Notifications','Mark All Read par click karte hi badge zero ho jayega.',`<button class="btn" onclick="markAllRead()">Mark All Read</button><div class="notification-panel">${items}</div>`,'Notification Center')}
function markAllRead(){notifyCount=0;localStorage.setItem('notifyCount',0);counts();toast('All notifications read');render('notifications')}
function messages(){return page('Messages','Message count bhi working hai.',`<button class="btn" onclick="msgCount=0;localStorage.setItem('msgCount',0);counts();render('messages');toast('Messages cleared')">Clear Messages</button>${msgCount?'<div class="list-item">💬 5 demo unread messages</div>':'<div class="empty">No unread messages.</div>'}`,'Messages')}
function users(){return page('Users','Users section ready hai. Firebase connect karne par real users show honge.',`<div class="empty">Abhi Firebase user data connected nahi hai.</div>`,'Users')}
function media(){return page('Media Manager','Images, PDF aur logo upload section.',`<div class="pro-upload" onclick="document.getElementById('mediaFile').click()"><input id="mediaFile" type="file" hidden onchange="showFileName(this)"><div class="upload-ring"><span>☁️</span></div><h2>Drag & Drop Media Here</h2><p id="fileName">Choose file: Image, PDF, Logo or Document</p><button class="btn" type="button">Choose File</button></div><div class="cards media-cards"><div class="stat-card">🖼 Logo</div><div class="stat-card">📄 PDF</div><div class="stat-card">📷 Images</div><div class="stat-card">📁 Files</div></div>`,'Media')}
function showFileName(input){const name=input.files&&input.files[0]?input.files[0].name:'No file selected';const e=document.getElementById('fileName');if(e)e.textContent='Selected: '+name;toast('Media file selected')}
function agecalc(){return page('Age Calculator','Date of Birth डालकर exact age calculate karein. Ye admin page par fully working hai.',`<div class="age-box"><div class="age-form"><label>Date of Birth</label><input id="dob" type="date"><button class="btn" onclick="calculateAge()">Calculate Age</button><button class="btn light" onclick="clearAge()">Clear</button></div><div id="ageResult" class="age-result"><div class="age-pill"><b>0</b><span>Years</span></div><div class="age-pill"><b>0</b><span>Months</span></div><div class="age-pill"><b>0</b><span>Days</span></div></div></div>`,'Smart Tool')}
function calculateAge(){const v=document.getElementById('dob')?.value;if(!v)return toast('Please select date of birth');const dob=new Date(v),now=new Date();if(dob>now)return toast('Future date valid nahi hai');let y=now.getFullYear()-dob.getFullYear();let m=now.getMonth()-dob.getMonth();let d=now.getDate()-dob.getDate();if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}document.getElementById('ageResult').innerHTML=`<div class="age-pill"><b>${y}</b><span>Years</span></div><div class="age-pill"><b>${m}</b><span>Months</span></div><div class="age-pill"><b>${d}</b><span>Days</span></div>`;toast('Age calculated')}
function clearAge(){const d=document.getElementById('dob');if(d)d.value='';document.getElementById('ageResult').innerHTML='<div class="age-pill"><b>0</b><span>Years</span></div><div class="age-pill"><b>0</b><span>Months</span></div><div class="age-pill"><b>0</b><span>Days</span></div>'}
function reports(){return page('Reports','Local posts ke basis par report chart.',`<canvas id="reportChart"></canvas>`,'Reports')}
function settings(){return page('Settings','Website basic settings.',`<div class="form-grid"><input value="Rapid Job"><input value="Fast Government Job Updates"></div><button class="btn" onclick="toast('Settings saved')">Save Settings</button>`,'Settings')}
const views={dashboard,content,manager,notifications,messages,users,media,reports,settings,ads,adsense,seo,agecalc};sections.forEach(s=>views[s.id]=()=>sectionPage(s));
function render(key){$('#content').innerHTML=(views[key]||dashboard)();$$('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===key||(['posts','admit','results','answers','admissions','scholarships','blogs','study','agecalc'].includes(key)&&b.dataset.view==='content')||(['ads','adsense','seo'].includes(key)&&b.dataset.view==='manager')));initCharts();if(innerWidth<900)$('#sidebar').classList.remove('show')}
function openPostForm(type='Latest Job'){$('#content').innerHTML=page('Add New Post','New content add karein.',form(type),'New Post')}
function initCharts(){const c=$('#reportChart');if(c&&!c.dataset.ok){c.dataset.ok=1;new Chart(c,{type:'bar',data:{labels:sections.map(s=>s.title),datasets:[{label:'Posts',data:sections.map(s=>posts.filter(p=>p.type===s.type).length),backgroundColor:'#8b5cf6'}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#69728a'}},y:{ticks:{color:'#69728a'}}}}})}}
$('#sideNav').addEventListener('click',e=>{const b=e.target.closest('button');if(b)render(b.dataset.view)});$('#quickPostBtn').onclick=()=>openPostForm('Latest Job');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('show');$('#notifyBtn').onclick=()=>render('notifications');$('#messageBtn').onclick=()=>render('messages');$('#backupBtn').onclick=()=>toast('Backup created successfully');$('#themeBtn').onclick=()=>document.documentElement.classList.toggle('dark');$('#searchInput').addEventListener('input',e=>{if(e.target.value.length>1)toast('Searching: '+e.target.value)});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});counts();render('dashboard');
