
/* Email + Secret Code Login */
const ADMIN_SECRET_CODE = "RJ2026";
const ADMIN_SESSION_KEY = "rapidJobAdminLogin";

function initAdminLogin(){
  const loginScreen = document.getElementById("adminLoginScreen");
  const emailInput = document.getElementById("adminEmail");
  const secretInput = document.getElementById("adminSecret");
  const loginBtn = document.getElementById("adminLoginBtn");
  const loginError = document.getElementById("loginError");
  const toggleSecret = document.getElementById("toggleSecret");
  const logoutBtn = document.getElementById("adminLogout");

  function unlockAdmin(){
    document.body.classList.remove("admin-locked");
    if(loginScreen) loginScreen.classList.add("hide");
  }

  function lockAdmin(){
    document.body.classList.add("admin-locked");
    if(loginScreen) loginScreen.classList.remove("hide");
  }

  if(localStorage.getItem(ADMIN_SESSION_KEY) === "yes"){
    unlockAdmin();
  }else{
    lockAdmin();
  }

  if(toggleSecret){
    toggleSecret.onclick = () => {
      if(!secretInput) return;
      secretInput.type = secretInput.type === "password" ? "text" : "password";
      toggleSecret.innerHTML = secretInput.type === "password" ? '<i class="fa-solid fa-eye"></i>' : '<i class="fa-solid fa-eye-slash"></i>';
    };
  }

  function doLogin(){
    const email = (emailInput?.value || "").trim();
    const code = (secretInput?.value || "").trim();

    if(!email || !email.includes("@")){
      if(loginError) loginError.textContent = "Please enter valid email address.";
      return;
    }

    if(code !== ADMIN_SECRET_CODE){
      if(loginError) loginError.textContent = "Wrong secret code.";
      if(secretInput) secretInput.focus();
      return;
    }

    localStorage.setItem(ADMIN_SESSION_KEY, "yes");
    if(loginError) loginError.textContent = "";
    unlockAdmin();
  }

  if(loginBtn) loginBtn.onclick = doLogin;
  if(secretInput) secretInput.addEventListener("keydown", e => { if(e.key === "Enter") doLogin(); });
  if(emailInput) emailInput.addEventListener("keydown", e => { if(e.key === "Enter") secretInput?.focus(); });

  if(logoutBtn){
    logoutBtn.onclick = () => {
      localStorage.removeItem(ADMIN_SESSION_KEY);
      if(secretInput) secretInput.value = "";
      lockAdmin();
    };
  }
}

document.addEventListener("DOMContentLoaded", initAdminLogin);


const firebaseConfig={apiKey:"AIzaSyBRLAUu228CbxbvokRG2Xp1hcGFhfrqpIQ",authDomain:"rapid-job-09.firebaseapp.com",databaseURL:"https://rapid-job-09-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"rapid-job-09",storageBucket:"rapid-job-09.firebasestorage.app",messagingSenderId:"129444686750",appId:"1:129444686750:web:6175ba1f1bfe7c9fff048f"};
firebase.initializeApp(firebaseConfig);const db=firebase.database();const $=q=>document.querySelector(q);let posts=[],messages=[],current="dashboard",editId=null;
const categories=[["job","Current Job"],["admit","Admit Card"],["result","Result"],["answer","Answer Key"],["admission","Admission"],["scholarship","Scholarship"],["syllabus","Syllabus"],["blog","Latest Blog"],["study","Study Material"],["yojana","Government Yojana"],["state","State Job"],["document","Document"],["new","New Update"]];
const demo={title:"RRB Ministerial & Isolated Categories Online Form 2026",updatedOn:"04 July 2026 10:42 PM",description:"Railway Recruitment Board (RRB) invites online applications for the recruitment of various ministerial and isolated categories posts. A total of 312 vacancies are available. Interested and eligible candidates can apply online from 30th December 2025 to 29th January 2026. Read the full notification before applying.",type:"job",state:"All India",status:"Published",featured:true,customBlocks:[{title:"Top Buttons",style:"buttons",content:"View All Jobs | index.html\nApply Online | #\nOfficial Website | #",order:1},{title:"Important Dates + Application Fee",style:"twoCard",content:"Important Dates\nApplication Start Date : 30-12-2025\nApplication Last Date : 29-01-2026\nFee Payment Last Date : 31-01-2026\nExam Date : 14 & 15 July 2026\n---\nApplication Fee\nSC / ST / Female / ESM / Minorities / EBC: Rs.250/-\nAll Other Candidates: Rs.500/-\nPayment can be made through Debit Card, Credit Card, Internet Banking or UPI.",order:10},{title:"Age Limit + Total Post",style:"twoCard",content:"Age Limit\nAge As On : 01.01.2026\nMinimum Age : 18 Years\nMaximum Age : See Below Post Wise\n---\nTotal Post\n312",order:20},{title:"Vacancy Details",style:"table",content:"Post Name | Pay Level | Total Post | Eligibility\nChief Law Assistant | Level-6 | 54 | Degree in Law with 3 Years Practice\nJunior Translator (Hindi) | Level-6 | 130 | Master Degree with Hindi & English",order:30},{title:"Selection Process",style:"card",content:"Computer Based Test (CBT)\nSkill Test / Typing Test (Post Wise)\nDocument Verification\nMedical Examination",order:40},{title:"Important Links",style:"yellowLinks",content:"Download Notification | Click Here For Notification | #\nApply Online | Click Here To Apply | #\nOfficial Website | Click Here To Open Official Website | #\nJoin Telegram Channel | Click Here To Join Telegram | #",order:100}]};
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function br(v){return esc(v).replaceAll("\n","<br>")}function catName(v){return (categories.find(c=>c[0]===v)||["",v||"Current Job"])[1]}
function page(t,s,b){return `<div class="hero"><span class="tag">Rapid Job CMS</span><h1>${t}</h1><p>${s}</p></div>${b}`}
function dashboard(){const pub=posts.filter(p=>p.status!=="Draft").length,draft=posts.filter(p=>p.status==="Draft").length;return page("Dashboard","Aapka visual job portal control center.",`<div class="stats"><div class="stat"><p>Total Posts</p><h2>${posts.length}</h2></div><div class="stat"><p>Published</p><h2>${pub}</h2></div><div class="stat"><p>Draft</p><h2>${draft}</h2></div><div class="stat"><p>Messages</p><h2>${messages.length}</h2></div></div><div class="panel"><div class="panel-head"><h2>Recent Posts</h2><button class="btn" onclick="openPostForm()">+ Add Post</button></div>${postTable(posts.slice(0,8))}</div>`)}
function postTable(list){return `<div class="table-wrap"><table class="table"><thead><tr><th>Title</th><th>Category</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>${list.map(p=>`<tr><td>${esc(p.title||"")}</td><td>${esc(catName(p.type))}</td><td><span class="badge ${p.status==='Draft'?'draft':''}">${esc(p.status||"Published")}</span></td><td>${esc(p.date||p.updatedOn||"")}</td><td><button class="mini view" onclick="previewSavedPost('${p.id}')">Preview</button><button class="mini edit" onclick="openPostForm('${p.id}')">Edit</button><button class="mini del" onclick="deletePost('${p.id}')">Delete</button></td></tr>`).join("")||'<tr><td colspan="5">No posts found.</td></tr>'}</tbody></table></div>`}
function postsPage(){return page("Post Management","Yahan se aap apne mann ke anusaar table, link, button, notice, card, HTML kuch bhi add kar sakte ho.",`<div class="panel"><div class="panel-head"><h2>All Posts</h2><button class="btn" onclick="openPostForm()">+ Add New Post</button></div>${postTable(posts)}</div>`)}
function input(id,label,value="",type="text"){return `<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${esc(value)}"></div>`}function textarea(id,label,value=""){return `<div class="field full"><label>${label}</label><textarea id="${id}">${esc(value)}</textarea></div>`}
function openPostForm(id=null){editId=id;const p=id?posts.find(x=>x.id===id)||demo:demo;$("#app").innerHTML=page(id?"Edit Post":"Add New Post","Visual CMS builder: section ka type select karo aur jo mann ho content add karo.",`<div class="panel"><div class="grid2"><div class="field"><label>Category</label><select id="type">${categories.map(c=>`<option value="${c[0]}" ${(p.type||p.category)===c[0]?"selected":""}>${c[1]}</option>`).join("")}</select></div><div class="field"><label>Status</label><select id="status"><option>Published</option><option>Draft</option><option>Pending</option></select></div><div class="field"><label>State</label><input id="state" value="${esc(p.state||"All India")}"></div><div class="field"><label>Featured / Trending</label><select id="featured"><option value="false">Normal Post</option><option value="true">Featured / Trending</option></select></div>${input("title","Post Title",p.title||"")}${input("updatedOn","Updated On",p.updatedOn||"")}${textarea("description","Top Short Information",p.description||p.details||"")}</div><div class="section-bar"><div><h2>Custom Visual Builder</h2><p class="hint">Line format: Table = Column1 | Column2 | Column3. Buttons = Button Text | URL. Yellow Link = Left | Right Text | URL.</p></div><button class="btn light" onclick="loadFastTemplate()">⚡ Add FastJob Template</button></div><div class="builder-toolbar"><button class="btn small light" onclick="addBlock('card')">+ Card</button><button class="btn small light" onclick="addBlock('twoCard')">+ Two Card</button><button class="btn small light" onclick="addBlock('table')">+ Table</button><button class="btn small light" onclick="addBlock('yellowLinks')">+ Yellow Links</button><button class="btn small light" onclick="addBlock('buttons')">+ Buttons</button><button class="btn small light" onclick="addBlock('notice')">+ Notice</button><button class="btn small light" onclick="addBlock('alert')">+ Alert</button><button class="btn small light" onclick="addBlock('html')">+ HTML</button><button class="btn small light" onclick="addBlock('faq')">+ FAQ</button><button class="btn small light" onclick="addBlock('image')">+ Image</button></div><div id="customBlocks"></div><div class="sticky-actions"><button class="btn preview" onclick="previewDraft()"><i class="fa-solid fa-eye"></i> Draft Preview</button><button class="btn light" onclick="savePost('Draft')"><i class="fa-solid fa-file-lines"></i> Save Draft</button><button class="btn green" onclick="savePost('Published')"><i class="fa-solid fa-paper-plane"></i> Publish Post</button><button class="btn light" onclick="render('posts')">Cancel</button></div></div>`);$("#status").value=p.status||"Published";$("#featured").value=String(!!p.featured||!!p.trending);(p.customBlocks&&p.customBlocks.length?p.customBlocks:demo.customBlocks).sort((a,b)=>(a.order||0)-(b.order||0)).forEach(b=>addBlock(b.style,b));}
function sample(style){const m={card:["Selection Process","Computer Based Test (CBT)\nDocument Verification",50],twoCard:["Important Dates + Fee","Important Dates\nStart Date : 01-01-2026\nLast Date : 31-01-2026\n---\nApplication Fee\nGeneral: Rs.500\nSC/ST: Rs.250",20],table:["Vacancy Details","Post Name | Total Post | Eligibility\nAssistant | 50 | Graduate\nClerk | 20 | 12th Pass",30],yellowLinks:["Important Links","Apply Online | Click Here To Apply | #\nDownload Notification | Click Here For Notification | #\nOfficial Website | Click Here To Open | #",100],buttons:["Top Buttons","View All Jobs | index.html\nApply Online | #\nOfficial Website | #",1],notice:["Important Notice","Read official notification before applying.",60],alert:["Latest Update","Application date extended.",5],html:["Custom HTML","<b>Write your custom HTML here</b>",70],faq:["FAQ","What is last date? | Check notification\nHow to apply? | Apply online",90],image:["Image/Banner","https://via.placeholder.com/900x250",45]};return m[style]||m.card}
function addBlock(style="card",data=null){const d=document.createElement("div");d.className="builder-row";const s=data?[data.title||"",data.content||"",data.order||50]:sample(style);d.innerHTML=`<input class="b-title" placeholder="Section Title" value="${esc(s[0])}"><select class="b-style"><option value="card">Card Box</option><option value="twoCard">Two Column Cards</option><option value="table">Table</option><option value="yellowLinks">Yellow Link Table</option><option value="buttons">Button Row</option><option value="notice">Notice Box</option><option value="alert">Alert Box</option><option value="faq">FAQ</option><option value="image">Image / Banner</option><option value="html">Custom HTML</option></select><textarea class="b-content" placeholder="Content">${esc(s[1])}</textarea><input class="b-order" type="number" value="${esc(s[2])}" placeholder="Order"><button class="mini del" onclick="this.parentElement.remove()">X</button>`;$("#customBlocks").appendChild(d);d.querySelector(".b-style").value=data?data.style||style:style}
function loadFastTemplate(){if(confirm("FastJob template add karna hai? Current custom blocks clear ho jayenge.")){$("#customBlocks").innerHTML="";demo.customBlocks.forEach(b=>addBlock(b.style,b))}}
function collectPostData(statusOverride=null){const get=id=>$("#"+id)?.value.trim()||"";const customBlocks=[...document.querySelectorAll(".builder-row")].map(r=>({title:r.querySelector(".b-title").value.trim(),style:r.querySelector(".b-style").value,content:r.querySelector(".b-content").value.trim(),order:Number(r.querySelector(".b-order").value||50)})).filter(b=>b.title||b.content).sort((a,b)=>a.order-b.order);const id=editId||("post_"+Date.now());return {id,type:get("type"),category:get("type"),section:get("type"),categoryName:catName(get("type")),status:statusOverride||get("status")||"Published",state:get("state")||"All India",featured:get("featured")==="true",trending:get("featured")==="true",title:get("title"),updatedOn:get("updatedOn"),description:get("description"),details:get("description"),customBlocks,time:Date.now(),date:new Date().toISOString().slice(0,10)}}
function renderBlock(b){const rows=String(b.content||"").split("\n").filter(x=>x.trim());if(b.style==="html")return `<div class="cms-card"><h3>${esc(b.title)}</h3>${b.content}</div>`;if(b.style==="image")return `<div class="cms-card"><h3>${esc(b.title)}</h3><img src="${esc(b.content)}" style="width:100%;border-radius:12px"></div>`;if(b.style==="notice"||b.style==="alert")return `<div class="cms-${b.style}"><b>${esc(b.title)}</b><br>${br(b.content)}</div>`;if(b.style==="buttons")return `<div class="cms-buttons">${rows.map(x=>{let [t,u]=x.split("|").map(y=>y?.trim()||"");return `<a href="${esc(u||'#')}" target="_blank">${esc(t||'Open')}</a>`}).join("")}</div>`;if(b.style==="yellowLinks")return `<h2>${esc(b.title)}</h2><table class="cms-table cms-links"><tbody>${rows.map(x=>{let [a,c,u]=x.split("|").map(y=>y?.trim()||"");return `<tr><td>${esc(a)}</td><td><a href="${esc(u||'#')}" target="_blank">${esc(c||'Click Here')}</a></td></tr>`}).join("")}</tbody></table>`;if(b.style==="table"){let table=rows.map(x=>x.split("|").map(y=>y.trim()));let head=table.shift()||[];return `<h2>${esc(b.title)}</h2><table class="cms-table"><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${table.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}if(b.style==="twoCard"){let parts=String(b.content||"").split("---");return `<div class="preview-grid">${parts.map(p=>{let l=p.trim().split("\n");let title=l.shift()||b.title;return `<div class="cms-card"><h3>${esc(title)}</h3><ul>${l.filter(Boolean).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`}).join("")}</div>`}if(b.style==="faq")return `<div class="cms-card"><h3>${esc(b.title)}</h3>${rows.map(x=>{let [q,a]=x.split("|");return `<p><b>Q.</b> ${esc(q||"")}<br><b>Ans:</b> ${esc(a||"Check details")}</p>`}).join("")}</div>`;return `<div class="cms-card"><h3>${esc(b.title)}</h3><ul>${rows.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`}
function previewHtml(d){return `<div class="preview-post"><div class="preview-head"><span class="tag">${esc(d.categoryName)}</span><h1>${esc(d.title||"Post Title")}</h1><p><i class="fa-regular fa-clock"></i> Updated On : ${esc(d.updatedOn||"")}</p></div><p>${br(d.description||"")}</p>${(d.customBlocks||[]).map(renderBlock).join("")}</div>`}
function ensureModal(){if(document.getElementById("adminModal"))return;let m=document.createElement("div");m.id="adminModal";m.className="admin-modal";m.innerHTML=`<div class="admin-modal-box wide"><button class="admin-modal-close" onclick="closeAdminModal()">×</button><div id="adminModalContent"></div></div>`;document.body.appendChild(m)}function openAdminModal(html){ensureModal();$("#adminModalContent").innerHTML=html;document.getElementById("adminModal").classList.add("show")}function closeAdminModal(){document.getElementById("adminModal")?.classList.remove("show")}
function alertPopup(m){openAdminModal(`<div class="modal-body"><h2>Success</h2><p>${esc(m)}</p><button class="btn" onclick="closeAdminModal()">OK</button></div>`)}function previewDraft(){let d=collectPostData();if(!d.title)return alert("Title required");openAdminModal(`<div class="modal-title-row"><h2>Post Preview Before Publish</h2><button class="btn green" onclick="closeAdminModal();savePost('Published')">Publish Now</button></div>${previewHtml(d)}`)}function previewSavedPost(id){let d=posts.find(p=>p.id===id);if(!d)return alert("Post not found");openAdminModal(`<div class="modal-title-row"><h2>${esc(d.title)}</h2><button class="btn" onclick="window.open('job-detail.html?id=${id}','_blank')">Open Page</button></div>${previewHtml(d)}`)}
async function savePost(status){let d=collectPostData(status);if(!d.title)return alert("Title required");await db.ref("posts/"+d.id).set(d);alertPopup(d.status==="Draft"?"Draft saved successfully.":"Post published successfully.");render("posts")}async function deletePost(id){if(confirm("Delete this post?")){await db.ref("posts/"+id).remove();alertPopup("Post deleted successfully.")}}
function messagesPage(){return page("Contact Messages","Contact page messages.",`<div class="panel">${messages.map(m=>`<div class="message-card"><b>${esc(m.name||"No Name")}</b><p>${esc(m.message||"")}</p></div>`).join("")||"No messages yet."}</div>`)}function breaking(){return page("Breaking News","Ticker update manage karein.",`<div class="panel"><textarea id="breakingText" style="width:100%;min-height:140px"></textarea><br><br><button class="btn" onclick="db.ref('settings/breakingNews').set($('#breakingText').value);alertPopup('Saved')">Save</button></div>`)}function media(){return page("Media Manager","Media links store karein.",`<div class="panel"><p>Use direct image/PDF URL in visual builder.</p></div>`)}function settings(){return page("Settings","Website settings.",`<div class="panel"><p>Rapid Job CMS settings.</p></div>`)}
function render(pageName=current){current=pageName;document.querySelectorAll("#sideNav button").forEach(b=>b.classList.toggle("active",b.dataset.page===pageName));const map={dashboard,posts:postsPage,messages:messagesPage,breaking,media,settings};$("#app").innerHTML=(map[pageName]||dashboard)();if(innerWidth<1000)$("#sidebar").classList.remove("show")}
function loadPosts(){db.ref("posts").on("value",s=>{posts=Object.entries(s.val()||{}).map(([id,p])=>({id,...p})).sort((a,b)=>(b.time||0)-(a.time||0));render(current)})}function loadMessages(){db.ref("contactMessages").on("value",s=>{messages=Object.entries(s.val()||{}).map(([id,m])=>({id,...m})).reverse();$("#msgBadge").textContent=messages.length;if(current==="messages")render(current)})}
document.addEventListener("click",e=>{if(e.target.id==="adminModal")closeAdminModal();let b=e.target.closest("#sideNav button");if(b)render(b.dataset.page)});$("#quickPost").onclick=()=>openPostForm();$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("show");$("#themeBtn").onclick=()=>document.documentElement.classList.toggle("dark");$("#searchInput").addEventListener("input",e=>{if(current!=="posts")return;let q=e.target.value.toLowerCase();$("#app").innerHTML=page("Search Results","Filtered posts.",`<div class="panel">${postTable(posts.filter(p=>(p.title||"").toLowerCase().includes(q)))}</div>`)});loadPosts();loadMessages();render();
